apiVersion: v1
kind: Service
metadata:
  name: token-eas-service
  labels:
    app: tokeneas
    service: tokeneas
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8090
  selector:
    app: tokeneas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-eas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tokeneas
      version: v1
  template:
    metadata:
      labels:
        app: tokeneas
        version: v1
    spec:
      containers:
      - image: token-eas-service:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: tokeneas
        ports:
        - containerPort: 8090